<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Form1.aspx.cs" Inherits="CrudTest.Form1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style5 {
            width: 398px;
        }
        .auto-style6 {
            font-size: x-large;
        }
        .auto-style7 {
            font-size: large;
        }
        .auto-style8 {
            width: 398px;
            height: 39px;
        }
        .auto-style9 {
            height: 39px;
        }
        .auto-style17 {
            width: 240px;
        }
        .auto-style21 {
            width: 117px;
            height: 17px;
        }
        .auto-style23 {
            width: 164px;
            height: 31px;
        }
        .auto-style24 {
            width: 206px;
            height: 31px;
        }
        .auto-style25 {
            margin-left: 0px;
        }
        .auto-style26 {
            width: 164px;
        }
        .auto-style27 {
            width: 149px;
        }
        .auto-style28 {
            width: 149px;
            height: 17px;
        }
        .auto-style29 {
            width: 191px;
        }
        </style>
</head>

<body>
   

    <form id="form1" runat="server">
        <div>
        </div>
        <table class="auto-style1">
            <tr>
                <td class="auto-style29">Enter Eno</td>
                <td class="auto-style17">
                    <asp:TextBox ID="txtempno" runat="server"></asp:TextBox>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </td>
                
                
            </tr>
            <tr>
                <td class="auto-style29">&nbsp;</td>
                
            </tr>
        </table>
        <table class="auto-style1">
            <tr>
                <td class="auto-style28">Enter Ename</td>
                <td class="auto-style21">
                    <asp:TextBox ID="txtempname" runat="server" CssClass="auto-style25" Height="22px" Width="180px"></asp:TextBox>
                </td>
                <a href="Form1.aspx">Form1.aspx</a>
               
            </tr>
            <tr>
                <td class="auto-style27">&nbsp;</td>
                
                
            </tr>
        </table>
        <table class="auto-style1">
            <tr>
                <td class="auto-style23">Enter salary</td>
                <td class="auto-style24">
                    <asp:TextBox ID="txtempsal" runat="server" CssClass="auto-style25"></asp:TextBox>
                </td>
                

            </tr>
            <tr>
                <td class="auto-style26">&nbsp;</td>
               
            </tr>
        </table>
        <table class="auto-style1">
            <tr>
                <td class="auto-style8">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Button ID="btnSave" runat="server" CssClass="auto-style7" OnClick="btnSave_Click" Text="Save" Width="99px" />
                    <div class="container">
</div>
                </td>
                <td class="auto-style9">
                    </td>
            </tr>
            <tr>
                <td class="auto-style5">
        <asp:GridView ID="GridView1" runat="server" CssClass="auto-style6" AutoGenerateColumns="False" CellPadding="3" GridLines="Vertical" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px">
            <AlternatingRowStyle BackColor="#DCDCDC" />
            <Columns>
                <asp:TemplateField HeaderText="EmpNo">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("eno") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("eno") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="EmpName">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("ename") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("ename") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="EmpSal">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("salary") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("salary") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
            <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
            <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
            <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#0000A9" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#000065" />
        </asp:GridView>
                </td>
                <td>&nbsp;</td>
            </tr>
        </table>
    </form>
</body>
</html>
