// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShivaStudents.Models;

#nullable disable

namespace ShivaEmployeeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShivaStudents.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Email = "Shiva@gmail.com",
                            Name = "Shiva",
                            Salary = 41000
                        },
                        new
                        {
                            EmployeeId = 2,
                            Email = "Krishna@gmail.com",
                            Name = "Krishna",
                            Salary = 78000
                        },
                        new
                        {
                            EmployeeId = 3,
                            Email = "Anand@gmail.com",
                            Name = "Anand",
                            Salary = 98000
                        },
                        new
                        {
                            EmployeeId = 4,
                            Email = "Anita@gmail.com",
                            Name = "Anita",
                            Salary = 89000
                        },
                        new
                        {
                            EmployeeId = 5,
                            Email = "Sharaddh@gmail.com",
                            Name = "Shraddha",
                            Salary = 59000
                        },
                        new
                        {
                            EmployeeId = 6,
                            Email = "Amisha@gmail.com",
                            Name = "Amisha",
                            Salary = 70000
                        },
                        new
                        {
                            EmployeeId = 7,
                            Email = "saurabh@gmail.com",
                            Name = "Saurabh",
                            Salary = 48000
                        },
                        new
                        {
                            EmployeeId = 8,
                            Email = "Tila@gmail.com",
                            Name = "Tilak",
                            Salary = 47900
                        },
                        new
                        {
                            EmployeeId = 9,
                            Email = "Paru@gmail.com",
                            Name = "Paru",
                            Salary = 41007
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
